theme: jekyll-theme-cayman
title: Welcome to the Azure DevOps Policy Pipeline Extension Docs

locale: en_US
#logo:

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Sebastian Schütze
  twitter: RazorSPoint
  linkedin: sebastianschuetze
  github: SebastianSchuetze
