title: Welcome to the Azure DevOps Policy Pipeline Extension Docs

locale: en_US
#logo:

owner:
  name: Sebastian Schütze
  twitter: RazorSPoint
  linkedin: sebastianschuetze
  github: SebastianSchuetze
  
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
